import { SettlementState, Vendor, StyleFolder, RoundData } from '@/lib/types';

const mockVendors: Vendor[] = [
  {
    id: 'vendor-01',
    code: '01',
    name: '로브로브',
    styles: [
      {
        id: 'style-0110',
        code: '0110',
        name: '애티튜드 가디건 정산표',
        rounds: [
          {
            id: 'round-0110-1',
            name: '1차',
            items: [
              { id: 'item-1', name: '블랙', quantity: 100, unitPrice: 25000 },
              { id: 'item-2', name: '크림', quantity: 80, unitPrice: 25000 },
            ],
            totalAmount: 4500000,
            depositPaidAmount: 1800000, // 40% of 4500000
            withVAT: true,
            files: [],
            createdAt: '2024-01-15T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0111',
        code: '0111',
        name: '지퍼니트',
        rounds: [
          {
            id: 'round-0111-1',
            name: '1차',
            items: [
              { id: 'item-1', name: '레귤러', quantity: 50, unitPrice: 18000 },
            ],
            totalAmount: 900000,
            depositPaidAmount: 360000,
            withVAT: false,
            files: [],
            createdAt: '2024-01-20T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0121',
        code: '0121',
        name: '후드니트',
        rounds: [
          {
            id: 'round-0121-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-01-25T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0130',
        code: '0130',
        name: '퀼팅 누빔 배색점퍼',
        rounds: [
          {
            id: 'round-0130-2',
            name: '2차',
            items: [
              { id: 'item-1', name: '블랙', quantity: 120, unitPrice: 32000 },
              { id: 'item-2', name: '크림', quantity: 100, unitPrice: 32000 },
            ],
            totalAmount: 7040000,
            depositPaidAmount: 2816000, // 40% of 7040000
            depositPaymentDate: '2024-02-01',
            balancePaymentDate: '2024-02-20',
            memo: '추가 주문분',
            withVAT: true,
            files: [
              { id: 'file-1', name: '0130 퀼팅 누빔 배색점퍼 계약금.pdf', type: 'pdf', uploadedAt: '2024-02-01T10:00:00Z' },
              { id: 'file-2', name: '0130 퀼팅 누빔 배색점퍼 잔금.pdf', type: 'pdf', uploadedAt: '2024-02-20T10:00:00Z' },
              { id: 'file-3', name: '0130 퀼팅 누빔 배색점퍼.xlsx', type: 'xlsx', uploadedAt: '2024-02-01T10:00:00Z' },
            ],
            createdAt: '2024-01-30T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0132',
        code: '0132',
        name: '스웨이드 자켓',
        rounds: [
          {
            id: 'round-0132-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-01T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0133',
        code: '0133',
        name: '브이넥 니트',
        rounds: [
          {
            id: 'round-0133-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-02T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0134',
        code: '0134',
        name: '퍼자켓',
        rounds: [
          {
            id: 'round-0134-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-03T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0136',
        code: '0136',
        name: '워크자켓',
        rounds: [
          {
            id: 'round-0136-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-04T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0137',
        code: '0137',
        name: '가죽 봄버자켓',
        rounds: [
          {
            id: 'round-0137-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-05T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0142',
        code: '0142',
        name: '여름니트',
        rounds: [
          {
            id: 'round-0142-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-06T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0144',
        code: '0144',
        name: '스노우집업 꽃플리스 자켓',
        rounds: [
          {
            id: 'round-0144-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-07T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0146',
        code: '0146',
        name: '후리스 베스트',
        rounds: [
          {
            id: 'round-0146-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-08T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0151',
        code: '0151',
        name: '무스탕',
        rounds: [
          {
            id: 'round-0151-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-09T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0152',
        code: '0152',
        name: '슬랙스',
        rounds: [
          {
            id: 'round-0152-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-10T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0153',
        code: '0153',
        name: '심플 울 니트',
        rounds: [
          {
            id: 'round-0153-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-11T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0155',
        code: '0155',
        name: '리파인 워크자켓',
        rounds: [
          {
            id: 'round-0155-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-12T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0157',
        code: '0157',
        name: '골 니트집업',
        rounds: [
          {
            id: 'round-0157-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-13T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0158',
        code: '0158',
        name: '베이직플리스 집업',
        rounds: [
          {
            id: 'round-0158-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-14T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0160',
        code: '0160',
        name: '아노락',
        rounds: [
          {
            id: 'round-0160-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-15T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0165',
        code: '0165',
        name: '간아웃 넥스카프 니트',
        rounds: [
          {
            id: 'round-0165-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-16T10:00:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'vendor-02',
    code: '02',
    name: '비브르',
    styles: [
      {
        id: 'style-0219',
        code: '0219',
        name: '스타일 0219',
        rounds: [
          {
            id: 'round-0219-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-17T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0221',
        code: '0221',
        name: '스타일 0221',
        rounds: [
          {
            id: 'round-0221-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-18T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0231',
        code: '0231',
        name: '스타일 0231',
        rounds: [
          {
            id: 'round-0231-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-19T10:00:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'vendor-05',
    code: '05',
    name: '편마',
    styles: [
      {
        id: 'style-0502',
        code: '0502',
        name: '메리노울 니트',
        rounds: [
          {
            id: 'round-0502-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-20T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0504',
        code: '0504',
        name: '가디건',
        rounds: [
          {
            id: 'round-0504-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-21T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0506',
        code: '0506',
        name: '자켓',
        rounds: [
          {
            id: 'round-0506-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-22T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0508',
        code: '0508',
        name: '가디건',
        rounds: [
          {
            id: 'round-0508-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-23T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0510',
        code: '0510',
        name: '헨리넥 니트',
        rounds: [
          {
            id: 'round-0510-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-24T10:00:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'vendor-07',
    code: '07',
    name: 'RMRN',
    styles: [
      {
        id: 'style-0701',
        code: '0701',
        name: '시스루 니트',
        rounds: [
          {
            id: 'round-0701-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-25T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0706',
        code: '0706',
        name: '세일러 집업',
        rounds: [
          {
            id: 'round-0706-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-26T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0710',
        code: '0710',
        name: '라운드 니트',
        rounds: [
          {
            id: 'round-0710-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-02-27T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0711',
        code: '0711',
        name: '4주차',
        rounds: [
          {
            id: 'round-0711-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-02-28T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0715',
        code: '0715',
        name: '가죽치마',
        rounds: [
          {
            id: 'round-0715-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-01T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0721',
        code: '0721',
        name: '항공점퍼',
        rounds: [
          {
            id: 'round-0721-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-03-02T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0722',
        code: '0722',
        name: '후드야상',
        rounds: [
          {
            id: 'round-0722-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-03T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0728',
        code: '0728',
        name: '스트라이프 가디건',
        rounds: [
          {
            id: 'round-0728-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-03-04T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0729',
        code: '0729',
        name: '울 가디건',
        rounds: [
          {
            id: 'round-0729-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-05T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0730',
        code: '0730',
        name: '스몰 티셔츠',
        rounds: [
          {
            id: 'round-0730-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-03-06T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0731',
        code: '0731',
        name: '미디움 티셔츠',
        rounds: [
          {
            id: 'round-0731-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-07T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0732',
        code: '0732',
        name: '라지 티셔츠',
        rounds: [
          {
            id: 'round-0732-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-03-08T10:00:00Z',
          },
        ],
      },
    ],
  },
  {
    id: 'vendor-08',
    code: '08',
    name: '솔드아웃',
    styles: [
      {
        id: 'style-0801',
        code: '0801',
        name: '모자',
        rounds: [
          {
            id: 'round-0801-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-09T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0802',
        code: '0802',
        name: '볼링니트',
        rounds: [
          {
            id: 'round-0802-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-03-10T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0803',
        code: '0803',
        name: '스타일 0803',
        rounds: [
          {
            id: 'round-0803-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-11T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0806',
        code: '0806',
        name: '스타일 0806',
        rounds: [
          {
            id: 'round-0806-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-03-12T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0807',
        code: '0807',
        name: '스타일 0807',
        rounds: [
          {
            id: 'round-0807-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-13T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0808',
        code: '0808',
        name: '토끼 아가일 니트',
        rounds: [
          {
            id: 'round-0808-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-03-14T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0810',
        code: '0810',
        name: '모자',
        rounds: [
          {
            id: 'round-0810-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-15T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0811',
        code: '0811',
        name: '긴팔패딩',
        rounds: [
          {
            id: 'round-0811-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: false,
            files: [],
            createdAt: '2024-03-16T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0812',
        code: '0812',
        name: '스타일 0812',
        rounds: [
          {
            id: 'round-0812-1',
            name: '1차',
            items: [],
            depositItems: [],
            totalAmount: 0,
            depositAmount: 0,
            balanceAmount: 0,
            depositPaidAmount: 0,
            withVAT: true,
            files: [],
            createdAt: '2024-03-17T10:00:00Z',
          },
        ],
      },
      {
        id: 'style-0133',
        code: '0133',
        name: '브이넥',
        rounds: [
          {
            id: 'round-0133-1',
            name: '1차',
            items: [
              { id: 'item-1', name: '아이보리(#2159)', colorCode: '#2159', quantity: 100, unitPrice: 23500 },
              { id: 'item-2', name: '멜란지 그레이(#2078)', colorCode: '#2078', quantity: 100, unitPrice: 23500 },
              { id: 'item-3', name: '스카이 블루(#2171)', colorCode: '#2171', quantity: 100, unitPrice: 23500 },
            ],
            totalAmount: 7050000,
            depositPaidAmount: 2820000, // 40% of 7050000
            depositPaymentDate: '2025-07-07',
            withVAT: true,
            files: [
              { id: 'file-1', name: '0133 브이넥 계약금.pdf', type: 'pdf', uploadedAt: '2025-07-07T10:00:00Z' },
            ],
            createdAt: '2025-07-07T10:00:00Z',
          },
        ],
      },
    ],
  },
];

export const getInitialState = (): SettlementState => {
  return {
    vendors: mockVendors,
    searchQuery: '',
    recentItems: [
      { vendorCode: '01', styleCode: '0133', roundName: '1차' },
      { vendorCode: '01', styleCode: '0130', roundName: '2차' },
    ],
  };
};

export const getMockVendors = (): Vendor[] => {
  return mockVendors;
};

export { mockVendors };
